### ISSUE TITLE
Cannot draw Canvas over navigation bar

### ISSUE THREAD

**Issue by Khosbayar** [deano2390/MaterialShowcaseView#179]
Does anyone know how to draw canvas with full height including navigation bar? It doesn't overdraw even I set canvas bitmap's height for full (measured height + navigation bar height).

![Screenshot_20190807-183812](https://user-images.githubusercontent.com/5780664/62669275-dd676900-b943-11e9-8cdc-1f2be379b2b8.png)

**Comment by Adam-GT** [comment]
Thank you for opening this issu @Khosbayar, I run in to the same problem on that. and I have figured out the issue.
it's because of  [this commit](https://github.com/deano2390/MaterialShowcaseView/pull/42/commits/06632f4de760bc71d1430e2c9bd8276a8a98c94f). 

Eventually the solution only checks if the device SDK is greater than or equals LOLLIPOP. but what they missed is that **Not all devices (SDK>=LOLLIPOP) have a Navigation Bar**.

Anyways ... Please post here if you have solved it or found some way to trick the library.

**Comment by adamGT** [comment]
Thank you for opening this issu @Khosbayar, I run in to the same problem on that. and I have figured out the issue.
it's because of this commit.

Eventually the solution only checks if the device SDK is greater than or equals LOLLIPOP. but what they missed is that Not all devices (SDK>=LOLLIPOP) have a Navigation Bar.

Anyways ... Please post here if you have solved it or found some way to trick the library.

**Comment by haldertaer** [comment]
I'm having the same issue. Does anyone know how to solve this?

**Comment by adamGT** [comment]
> I'm having the same issue. Does anyone know how to solve this?

if your using it as a user guide,I recommend to try another method like a quick Tutorial gif , that's what I did, but if you need this library, You can create a child class which extends **MaterialShowcaseView** and override all of it and change the 319 line(contentLP.bottomMargin = mBottomMargin;) ot (contentLP.bottomMargin = 0;). 
It have major disadvantages but that would be a quick fix.

**Comment by Ryanhustler420** [comment]
use `.renderOverNavigationBar()` chain method.
